apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
        - name: sql
          image: gcr.io/dallas-lake/strum-sql:v1 # Replace with your actual image details
          env:
            - name: POSTGRES_DB
              value: "postgres"  # Set your PostgreSQL database name
            - name: POSTGRES_HOST
              value: "postgresql"  # Set your PostgreSQL host (service name)
            - name: POSTGRES_PORT
              value: "5432"  # Set your PostgreSQL port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgre-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgre-secret
                  key: password  
