apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: NodePort
  selector:
    app: postgresql  # Use the labels that match your PostgreSQL pods
  ports:
    - protocol: TCP
      port: 5432  # Port on the service
      targetPort: 5432  # Port on the pods
